/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck
         * @description Retorna 200 OK se a API está no ar e o banco SQLite responde a uma query trivial. Usado para smoke tests e orquestração local.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versões dos componentes
         * @description Versão da API, do schema do banco e do solver subjacente.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/criteria-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfis de critério de utilização disponíveis
         * @description Lista os 4 perfis suportados (MVP_Preliminary, API_RP_2SK, DNV_placeholder, UserDefined) com seus limites default. Para UserDefined, os limites são fornecidos no request e este endpoint retorna placeholders.
         */
        get: operations["list_criteria_profiles_api_v1_criteria_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar casos
         * @description Lista casos salvos, paginados e ordenados por updated_at desc. Use `search` para filtrar por nome.
         */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /**
         * Criar caso
         * @description Valida e persiste um novo caso. Retorna o caso com id e timestamps.
         */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhar caso
         * @description Retorna o input completo do caso e até as últimas 10 execuções (mais recentes primeiro).
         */
        get: operations["get_case_api_v1_cases__case_id__get"];
        /**
         * Atualizar caso
         * @description Substitui o input do caso. Execuções anteriores são preservadas.
         */
        put: operations["update_case_api_v1_cases__case_id__put"];
        post?: never;
        /**
         * Remover caso
         * @description Remove o caso e todas as suas execuções (cascade via ON DELETE CASCADE). Retorna corpo vazio.
         */
        delete: operations["delete_case_api_v1_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Executar solver no caso
         * @description Invoca o solver de catenária estática no caso salvo. Persiste a execução no histórico (mantém últimas 10 por caso) e retorna o resultado completo.
         *
         *     HTTP response codes:
         *     - **200** se o solver convergiu ou detectou caso mal-condicionado
         *     - **200** (com `status=max_iterations`) se atingiu limite sem convergir
         *     - **422** se o caso é fisicamente inviável (`invalid_case` ou `numerical_error`); o body ainda inclui o SolverResult
         */
        post: operations["solve_case_api_v1_cases__case_id__solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run do solver (não persiste)
         * @description Recebe um `CaseInput` completo no body, executa o solver e retorna o `SolverResult`. **Não** cria caso nem execução no banco — use para análises paramétricas ao vivo (ex: slider no frontend).
         *
         *     Para fluxo com persistência, veja `POST /cases/{id}/solve`.
         *
         *     HTTP response codes:
         *     - **200** se convergiu ou ill_conditioned ou max_iterations
         *     - **422** se o caso é fisicamente inviável; body inclui SolverResult completo
         */
        post: operations["preview_solve_api_v1_solve_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tipos de linha
         * @description Lista paginada do catálogo. Filtros: `category`, `search` (ILIKE em line_type), `diameter_min`, `diameter_max`.
         */
        get: operations["list_line_types_api_v1_line_types_get"];
        put?: never;
        /**
         * Cadastrar tipo user_input
         * @description Cria uma nova entrada com `data_source='user_input'`. As 522 entradas legacy_qmoor não podem ser modificadas; use este endpoint para adicionar tipos próprios.
         */
        post: operations["create_line_type_api_v1_line_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-types/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar por (line_type, diameter)
         * @description Retorna a entrada que combina exatamente `line_type` (nome) e `diameter` (em metros). Útil para resolver um segmento do solver via identificador + dimensão.
         */
        get: operations["lookup_line_type_api_v1_line_types_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-types/{line_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhar tipo de linha por id */
        get: operations["get_line_type_api_v1_line_types__line_type_id__get"];
        /**
         * Editar tipo user_input
         * @description Só permite edição de entradas com `data_source='user_input'`. Entradas `legacy_qmoor` são imutáveis (retorna 403).
         */
        put: operations["update_line_type_api_v1_line_types__line_type_id__put"];
        post?: never;
        /**
         * Remover tipo user_input
         * @description Apenas entradas `user_input` podem ser removidas.
         */
        delete: operations["delete_line_type_api_v1_line_types__line_type_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/moor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar caso no formato .moor
         * @description Aceita JSON body no schema da Seção 5.2 do MVP v2 PDF. Campos quantitativos podem vir como strings com unidade ("450 ft", "13.78 lbf/ft") ou números puros (usa unidade padrão do `unitSystem`).
         *
         *     Exemplo minimal (imperial):
         *     ```json
         *     {"name": "Import test", "unitSystem": "imperial",
         *      "mooringLine": {"name": "ML1",
         *       "segments": [{"category": "Wire",
         *         "length": "1476.4 ft",
         *         "lineProps": {"lineType": "IWRCEIPS",
         *           "diameter": "3 in", "breakStrength": "850 kip",
         *           "wetWeight": "13.78 lbf/ft", "dryWeight": "16.6 lbf/ft",
         *           "modulus": "9804 kip/in^2", "seabedFrictionCF": 0.6}}],
         *       "boundary": {"startpointDepth": "0 ft",
         *         "endpointDepth": "984 ft", "endpointGrounded": true},
         *       "solution": {"inputParam": "Tension",
         *         "fairleadTension": "150 kip"}}}
         *     ```
         */
        post: operations["import_moor_api_v1_import_moor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/export/moor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar caso como .moor
         * @description Serializa o caso no schema .moor (Seção 5.2 MVP v2). Escolha o `unit_system` — `imperial` ou `metric`. Valores SI internos são convertidos para a unidade de saída.
         */
        get: operations["export_moor_api_v1_cases__case_id__export_moor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/export/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar caso como JSON normalizado
         * @description Retorna o `CaseOutput` completo (input em SI + últimas execuções). Equivalente a GET /cases/{id}, mas tem rota explícita de export.
         */
        get: operations["export_json_api_v1_cases__case_id__export_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/export/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar relatório técnico em PDF
         * @description Gera um relatório técnico em PDF A4 com:
         *     1. Header (caso, timestamp, solver version)
         *     2. Disclaimer técnico obrigatório (Seção 10 do Documento A v2.2)
         *     3. Tabela de inputs
         *     4. Gráfico 2D do perfil da linha (matplotlib)
         *     5. Tabela de resultados com alert level colorido
         *     6. Status e mensagem do solver
         *
         *     Usa a **última execução** do caso. Se o caso nunca foi resolvido, gera um relatório parcial apenas com as entradas.
         */
        get: operations["export_pdf_api_v1_cases__case_id__export_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertLevel
         * @description Classificação da utilização T_fl/MBL (Seção 5 do Documento A v2.2).
         *
         *     - ok:     utilização abaixo do limite amarelo (linha em regime normal)
         *     - yellow: atenção (padrão: T/MBL ≥ 0,50)
         *     - red:    limite operacional intacto atingido (padrão: T/MBL ≥ 0,60)
         *     - broken: linha rompida matemáticamente (T/MBL ≥ 1,00 → INVALID_CASE)
         * @enum {string}
         */
        AlertLevel: "ok" | "yellow" | "red" | "broken";
        /**
         * BoundaryConditions
         * @description Condições de contorno físicas do problema.
         *
         *     h é a distância vertical da âncora até o fairlead (positiva = fairlead
         *     acima da âncora). No modelo de fundo plano, h coincide com a lâmina
         *     d'água se a âncora está no seabed.
         *
         *     Campos `startpoint_depth` e `endpoint_grounded` refletem Seção 5.1 do
         *     MVP v2 PDF. O MVP v1 assume:
         *       - fairlead (startpoint) na superfície → startpoint_depth = 0
         *       - âncora (endpoint) no seabed         → endpoint_grounded = True
         *     Valores diferentes são validados pelo facade solve() e geram INVALID_CASE
         *     com mensagem clara. Suporte para âncora elevada fica para v2+.
         */
        BoundaryConditions: {
            /**
             * H
             * @description Distância vertical anchor→fairlead (m)
             */
            h: number;
            mode: components["schemas"]["SolutionMode"];
            /**
             * Input Value
             * @description T_fl (N) se mode=Tension; X_total (m) se mode=Range
             */
            input_value: number;
            /**
             * Startpoint Depth
             * @description Profundidade do fairlead abaixo da superfície (m). MVP v1: sempre 0.
             * @default 0
             */
            startpoint_depth: number;
            /**
             * Endpoint Grounded
             * @description Se True, âncora está no seabed. MVP v1 exige True.
             * @default true
             */
            endpoint_grounded: boolean;
        };
        /**
         * CaseInput
         * @description Input canônico para criar ou atualizar um caso (Seção 4.1 do plano F2).
         * @example {
         *       "boundary": {
         *         "endpoint_grounded": true,
         *         "h": 300,
         *         "input_value": 785000,
         *         "mode": "Tension",
         *         "startpoint_depth": 0
         *       },
         *       "criteria_profile": "MVP_Preliminary",
         *       "description": "Wire rope 3in, lâmina 300 m, T_fl=785 kN",
         *       "name": "BC-01 — catenária pura suspensa",
         *       "seabed": {
         *         "mu": 0
         *       },
         *       "segments": [
         *         {
         *           "EA": 34250000,
         *           "MBL": 3780000,
         *           "category": "Wire",
         *           "length": 450,
         *           "line_type": "IWRCEIPS",
         *           "w": 201.1
         *         }
         *       ]
         *     }
         */
        CaseInput: {
            /**
             * Name
             * @description Nome do caso
             */
            name: string;
            /**
             * Description
             * @description Descrição livre (opcional)
             */
            description?: string | null;
            /**
             * Segments
             * @description Lista de segmentos (1 ou mais, F5.1). Para uma linha composta típica use 3 segmentos (chain pendant inferior + wire + chain pendant superior). Ordem do segmento 0 (mais próximo da âncora) ao último (mais próximo do fairlead).
             */
            segments: components["schemas"]["LineSegment"][];
            boundary: components["schemas"]["BoundaryConditions"];
            seabed?: components["schemas"]["SeabedConfig"];
            /** @default MVP_Preliminary */
            criteria_profile: components["schemas"]["CriteriaProfile"];
            /** @description Obrigatório quando criteria_profile = UserDefined. */
            user_defined_limits?: components["schemas"]["UtilizationLimits"] | null;
            /**
             * Attachments
             * @description Boias ou clump weights pontuais nas junções entre segmentos (F5.2). Cada attachment fica em `position_index` (0 = entre seg 0 e seg 1). Lista vazia para linha sem elementos pontuais.
             */
            attachments?: components["schemas"]["LineAttachment"][];
        };
        /**
         * CaseOutput
         * @description Representação detalhada (para GET /cases/{id}).
         */
        CaseOutput: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            input: components["schemas"]["CaseInput"];
            /**
             * Latest Executions
             * @description Últimas 10 execuções (mais recente primeiro). Vazio se nunca foi resolvido.
             */
            latest_executions?: components["schemas"]["ExecutionOutput"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CaseSummary
         * @description Versão enxuta do caso para listagem (sem input completo).
         */
        CaseSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Line Type
             * @description Primeiro segmento.line_type (se informado)
             */
            line_type?: string | null;
            /**
             * Mode
             * @example Tension
             * @example Range
             */
            mode: string;
            /**
             * Water Depth
             * @description Lâmina d'água em metros
             */
            water_depth: number;
            /**
             * Line Length
             * @description Comprimento da linha em metros
             */
            line_length: number;
            /** Criteria Profile */
            criteria_profile: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConvergenceStatus
         * @description Estados finais do solver (Documento A v2.2, Seção 3.5.5).
         * @enum {string}
         */
        ConvergenceStatus: "converged" | "max_iterations" | "invalid_case" | "numerical_error" | "ill_conditioned";
        /**
         * CriteriaProfile
         * @description Perfis de critério de utilização (Seção 5 do Documento A v2.2, resposta P-04).
         *
         *     - MVP_Preliminary: default simples, 0.50/0.60/1.00
         *     - API_RP_2SK:      intacto 0.60, danificado 0.80 (ainda 1.00 para broken)
         *     - DNV_placeholder: reservado para ULS/ALS/FLS; tratado como MVP até F4+
         *     - UserDefined:     usuário fornece yellow/red/broken ratios
         * @enum {string}
         */
        CriteriaProfile: "MVP_Preliminary" | "API_RP_2SK" | "DNV_placeholder" | "UserDefined";
        /**
         * CriteriaProfileInfo
         * @description Descrição de um perfil de critério de utilização.
         */
        CriteriaProfileInfo: {
            /**
             * Name
             * @description Identificador do perfil (usado como valor de criteria_profile).
             * @example MVP_Preliminary
             */
            name: string;
            /**
             * Yellow Ratio
             * @description Limite T_fl/MBL para alerta amarelo.
             * @example 0.5
             */
            yellow_ratio: number;
            /**
             * Red Ratio
             * @description Limite T_fl/MBL para alerta vermelho.
             * @example 0.6
             */
            red_ratio: number;
            /**
             * Broken Ratio
             * @description T_fl/MBL a partir do qual o caso vira INVALID_CASE.
             * @example 1
             */
            broken_ratio: number;
            /**
             * Description
             * @description Explicação curta do perfil.
             */
            description: string;
        };
        /**
         * ErrorDetail
         * @description Corpo interno do envelope de erro.
         */
        ErrorDetail: {
            /**
             * Code
             * @description Identificador da classe de erro (ex: 'case_not_found').
             * @example case_not_found
             */
            code: string;
            /**
             * Message
             * @description Mensagem legível em português para exibir ao usuário.
             */
            message: string;
            /**
             * Detail
             * @description Metadados opcionais (ex: snapshot de SolverResult).
             */
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ErrorResponse
         * @description Envelope padrão de erro da API.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ExecutionOutput
         * @description Representação de uma execução persistida.
         */
        ExecutionOutput: {
            /** Id */
            id: number;
            /** Case Id */
            case_id: number;
            result: components["schemas"]["SolverResult"];
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Resposta do healthcheck.
         */
        HealthResponse: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * Db
             * @description Estado do banco
             * @example ok
             */
            db: string;
        };
        /**
         * LineAttachment
         * @description Elemento pontual ao longo da linha — boia (empuxo líquido) ou clump
         *     weight (peso adicional). F5.2.
         *
         *     Convenção: attachments são posicionados em **junções entre segmentos**
         *     (não no meio de um segmento). Para colocar uma boia no meio de uma
         *     linha homogênea, divida em 2 segmentos idênticos e ponha a boia entre
         *     eles.
         *
         *     `submerged_force` é magnitude positiva (N). A direção física é
         *     determinada pelo `kind`:
         *       - `clump_weight`: tende a puxar a linha para BAIXO → V += force
         *       - `buoy`:         tende a empurrar a linha para CIMA  → V −= force
         *
         *     `position_index` é zero-based: 0 = junção entre segmento 0 e 1.
         *     Range válido: 0 .. len(segments) − 2.
         */
        LineAttachment: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "clump_weight" | "buoy";
            /**
             * Submerged Force
             * @description Força submersa líquida em N (sempre positiva)
             */
            submerged_force: number;
            /**
             * Position Index
             * @description Índice da junção (0 = entre segmento 0 e 1). Deve ser < N-1 onde N é o número de segmentos.
             */
            position_index: number;
            /**
             * Name
             * @description Identificador legível para relatórios (ex.: 'Boia A')
             */
            name?: string | null;
        };
        /**
         * LineSegment
         * @description Segmento homogêneo de linha de ancoragem.
         *
         *     Grandezas em SI: comprimento em m, peso em N/m, EA e MBL em N.
         *     MVP v2 suporta uma única linha, portanto um único segmento.
         *     Multi-segmento fica para v2.1 (conforme Seção 9 do Documento A).
         *
         *     Campos opcionais `category` e `line_type` refletem Seção 5.1 do MVP v2
         *     PDF e Seção 4.2 do Documento A; servem para rastreabilidade e para
         *     escolher defaults de atrito na Seção 4.4 quando o solo é conhecido.
         *     Não afetam o cálculo do solver.
         */
        LineSegment: {
            /**
             * Length
             * @description Comprimento não-esticado (m)
             */
            length: number;
            /**
             * W
             * @description Peso submerso por unidade de comprimento (N/m)
             */
            w: number;
            /**
             * Ea
             * @description Rigidez axial do segmento (N)
             */
            EA: number;
            /**
             * Mbl
             * @description Minimum Breaking Load (N)
             */
            MBL: number;
            /**
             * Category
             * @description Wire, StuddedChain, StudlessChain ou Polyester
             */
            category?: ("Wire" | "StuddedChain" | "StudlessChain" | "Polyester") | null;
            /**
             * Line Type
             * @description Identificador no catálogo (ex.: 'IWRCEIPS', 'R4Studless')
             */
            line_type?: string | null;
            /**
             * Diameter
             * @description Diâmetro nominal (m) — metadado
             */
            diameter?: number | null;
            /**
             * Dry Weight
             * @description Peso seco por unidade (N/m) — metadado
             */
            dry_weight?: number | null;
            /**
             * Modulus
             * @description Módulo axial aparente (Pa) — metadado
             */
            modulus?: number | null;
        };
        /**
         * LineTypeCreate
         * @description Payload para POST /line-types (sempre user_input).
         * @example {
         *       "break_strength": 5000000,
         *       "category": "Wire",
         *       "diameter": 0.076,
         *       "dry_weight": 180,
         *       "line_type": "MyCustomWire",
         *       "manufacturer": "Acme",
         *       "modulus": 100000000000,
         *       "qmoor_ea": 80000000,
         *       "seabed_friction_cf": 0.3,
         *       "wet_weight": 150
         *     }
         */
        LineTypeCreate: {
            /**
             * Line Type
             * @example IWRCEIPS
             */
            line_type: string;
            /**
             * Category
             * @enum {string}
             */
            category: "Wire" | "StuddedChain" | "StudlessChain" | "Polyester";
            /**
             * Base Unit System
             * @description Sistema de origem. Valores no payload estão SEMPRE em SI.
             * @default metric
             * @enum {string}
             */
            base_unit_system: "imperial" | "metric";
            /**
             * Diameter
             * @description Diâmetro (m)
             */
            diameter: number;
            /**
             * Dry Weight
             * @description Peso seco por unidade (N/m)
             */
            dry_weight: number;
            /**
             * Wet Weight
             * @description Peso submerso por unidade (N/m)
             */
            wet_weight: number;
            /**
             * Break Strength
             * @description MBL (N)
             */
            break_strength: number;
            /**
             * Modulus
             * @description Módulo (Pa)
             */
            modulus?: number | null;
            /**
             * Qmoor Ea
             * @description EA QMoor (N)
             */
            qmoor_ea?: number | null;
            /**
             * Gmoor Ea
             * @description EA GMoor (N)
             */
            gmoor_ea?: number | null;
            /**
             * Seabed Friction Cf
             * @description Coef. atrito seabed (adimensional)
             */
            seabed_friction_cf: number;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Comments */
            comments?: string | null;
        };
        /**
         * LineTypeOutput
         * @description Item retornado pelos endpoints de listagem e detalhe.
         */
        LineTypeOutput: {
            /**
             * Line Type
             * @example IWRCEIPS
             */
            line_type: string;
            /**
             * Category
             * @enum {string}
             */
            category: "Wire" | "StuddedChain" | "StudlessChain" | "Polyester";
            /**
             * Base Unit System
             * @description Sistema de origem. Valores no payload estão SEMPRE em SI.
             * @default metric
             * @enum {string}
             */
            base_unit_system: "imperial" | "metric";
            /**
             * Diameter
             * @description Diâmetro (m)
             */
            diameter: number;
            /**
             * Dry Weight
             * @description Peso seco por unidade (N/m)
             */
            dry_weight: number;
            /**
             * Wet Weight
             * @description Peso submerso por unidade (N/m)
             */
            wet_weight: number;
            /**
             * Break Strength
             * @description MBL (N)
             */
            break_strength: number;
            /**
             * Modulus
             * @description Módulo (Pa)
             */
            modulus?: number | null;
            /**
             * Qmoor Ea
             * @description EA QMoor (N)
             */
            qmoor_ea?: number | null;
            /**
             * Gmoor Ea
             * @description EA GMoor (N)
             */
            gmoor_ea?: number | null;
            /**
             * Seabed Friction Cf
             * @description Coef. atrito seabed (adimensional)
             */
            seabed_friction_cf: number;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Comments */
            comments?: string | null;
            /** Id */
            id: number;
            /** Legacy Id */
            legacy_id: number | null;
            /**
             * Data Source
             * @enum {string}
             */
            data_source: "legacy_qmoor" | "manufacturer" | "certificate" | "user_input";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LineTypeUpdate
         * @description Payload para PUT /line-types/{id}.
         */
        LineTypeUpdate: {
            /**
             * Line Type
             * @example IWRCEIPS
             */
            line_type: string;
            /**
             * Category
             * @enum {string}
             */
            category: "Wire" | "StuddedChain" | "StudlessChain" | "Polyester";
            /**
             * Base Unit System
             * @description Sistema de origem. Valores no payload estão SEMPRE em SI.
             * @default metric
             * @enum {string}
             */
            base_unit_system: "imperial" | "metric";
            /**
             * Diameter
             * @description Diâmetro (m)
             */
            diameter: number;
            /**
             * Dry Weight
             * @description Peso seco por unidade (N/m)
             */
            dry_weight: number;
            /**
             * Wet Weight
             * @description Peso submerso por unidade (N/m)
             */
            wet_weight: number;
            /**
             * Break Strength
             * @description MBL (N)
             */
            break_strength: number;
            /**
             * Modulus
             * @description Módulo (Pa)
             */
            modulus?: number | null;
            /**
             * Qmoor Ea
             * @description EA QMoor (N)
             */
            qmoor_ea?: number | null;
            /**
             * Gmoor Ea
             * @description EA GMoor (N)
             */
            gmoor_ea?: number | null;
            /**
             * Seabed Friction Cf
             * @description Coef. atrito seabed (adimensional)
             */
            seabed_friction_cf: number;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Serial Number */
            serial_number?: string | null;
            /** Comments */
            comments?: string | null;
        };
        /** PaginatedResponse[CaseSummary] */
        PaginatedResponse_CaseSummary_: {
            /** Items */
            items: components["schemas"]["CaseSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaginatedResponse[LineTypeOutput] */
        PaginatedResponse_LineTypeOutput_: {
            /** Items */
            items: components["schemas"]["LineTypeOutput"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * SeabedConfig
         * @description Configuração do seabed (assumido plano e horizontal no MVP v1).
         */
        SeabedConfig: {
            /**
             * Mu
             * @description Coeficiente de atrito axial
             * @default 0
             */
            mu: number;
        };
        /**
         * SolutionMode
         * @description Modo de solução — qual grandeza é input, qual é output.
         * @enum {string}
         */
        SolutionMode: "Tension" | "Range";
        /**
         * SolverResult
         * @description Saída completa do solver.
         *
         *     Campos obrigatórios conforme Seção 6 da Documentação MVP v2:
         *       coords.x/y, tension.x/y, fairleadTension, totalHorzDistance,
         *       endpointDepth, stretchedLength/unstretchedLength, elongation,
         *       distToFirstTD, totalGroundedLength, suspendedLength/totalSuspendedLength,
         *       angleWRThorz/angleWRTvert.
         *
         *     Campos adicionais (H, iterations_used, …) são diagnósticos internos.
         */
        SolverResult: {
            status: components["schemas"]["ConvergenceStatus"];
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Coords X
             * @description x (m)
             */
            coords_x?: number[];
            /**
             * Coords Y
             * @description y (m)
             */
            coords_y?: number[];
            /**
             * Tension X
             * @description T_horizontal (N) por nó
             */
            tension_x?: number[];
            /**
             * Tension Y
             * @description T_vertical (N) por nó
             */
            tension_y?: number[];
            /**
             * Tension Magnitude
             * @description |T| (N) por nó
             */
            tension_magnitude?: number[];
            /**
             * Fairlead Tension
             * @default 0
             */
            fairlead_tension: number;
            /**
             * Anchor Tension
             * @default 0
             */
            anchor_tension: number;
            /**
             * Total Horz Distance
             * @default 0
             */
            total_horz_distance: number;
            /**
             * Endpoint Depth
             * @default 0
             */
            endpoint_depth: number;
            /**
             * Unstretched Length
             * @default 0
             */
            unstretched_length: number;
            /**
             * Stretched Length
             * @default 0
             */
            stretched_length: number;
            /**
             * Elongation
             * @default 0
             */
            elongation: number;
            /**
             * Total Suspended Length
             * @default 0
             */
            total_suspended_length: number;
            /**
             * Total Grounded Length
             * @default 0
             */
            total_grounded_length: number;
            /** Dist To First Td */
            dist_to_first_td?: number | null;
            /**
             * Angle Wrt Horz Fairlead
             * @default 0
             */
            angle_wrt_horz_fairlead: number;
            /**
             * Angle Wrt Vert Fairlead
             * @default 0
             */
            angle_wrt_vert_fairlead: number;
            /**
             * Angle Wrt Horz Anchor
             * @default 0
             */
            angle_wrt_horz_anchor: number;
            /**
             * Angle Wrt Vert Anchor
             * @default 0
             */
            angle_wrt_vert_anchor: number;
            /**
             * H
             * @default 0
             */
            H: number;
            /**
             * Iterations Used
             * @default 0
             */
            iterations_used: number;
            /**
             * Utilization
             * @default 0
             */
            utilization: number;
            /** @default ok */
            alert_level: components["schemas"]["AlertLevel"];
            /**
             * Water Depth
             * @default 0
             */
            water_depth: number;
            /**
             * Startpoint Depth
             * @default 0
             */
            startpoint_depth: number;
            /**
             * Solver Version
             * @default
             */
            solver_version: string;
            /** Segment Boundaries */
            segment_boundaries?: number[];
        };
        /**
         * UtilizationLimits
         * @description Limites absolutos de T_fl/MBL que disparam cada AlertLevel.
         *
         *     A ordem deve ser: yellow_ratio < red_ratio < broken_ratio.
         */
        UtilizationLimits: {
            /**
             * Yellow Ratio
             * @default 0.5
             */
            yellow_ratio: number;
            /**
             * Red Ratio
             * @default 0.6
             */
            red_ratio: number;
            /**
             * Broken Ratio
             * @default 1
             */
            broken_ratio: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionResponse
         * @description Resposta do endpoint /version.
         */
        VersionResponse: {
            /**
             * Api
             * @example 0.1.0
             */
            api: string;
            /**
             * Schema Version
             * @example 1
             */
            schema_version: string;
            /**
             * Solver
             * @example 1.0.0
             */
            solver: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    list_criteria_profiles_api_v1_criteria_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriteriaProfileInfo"][];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: {
                /** @description Página (1-indexed). */
                page?: number;
                /** @description Itens por página (máx. 100). */
                page_size?: number;
                /** @description Filtro ILIKE sobre o nome do caso. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_CaseSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutput"];
                };
            };
            /** @description Entrada inválida (Pydantic validation). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutput"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_v1_cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutput"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_case_api_v1_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_case_api_v1_cases__case_id__solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionOutput"];
                };
            };
            /** @description Caso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caso inviável fisicamente (T_fl ≤ w·h, linha rompida, âncora elevada, etc.). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_solve_api_v1_solve_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_line_types_api_v1_line_types_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                category?: ("Wire" | "StuddedChain" | "StudlessChain" | "Polyester") | null;
                search?: string | null;
                diameter_min?: number | null;
                diameter_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_LineTypeOutput_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_line_type_api_v1_line_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineTypeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineTypeOutput"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lookup_line_type_api_v1_line_types_lookup_get: {
        parameters: {
            query: {
                /** @description Nome do tipo (ex: 'IWRCEIPS') */
                line_type: string;
                /** @description Diâmetro em metros */
                diameter: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineTypeOutput"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_type_api_v1_line_types__line_type_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                line_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineTypeOutput"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_line_type_api_v1_line_types__line_type_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                line_type_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineTypeOutput"];
                };
            };
            /** @description Entrada legacy_qmoor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_line_type_api_v1_line_types__line_type_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                line_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_moor_api_v1_import_moor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutput"];
                };
            };
            /** @description Schema .moor inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversão para SI falhou */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_moor_api_v1_cases__case_id__export_moor_get: {
        parameters: {
            query?: {
                /** @description Sistema de unidades da saída */
                unit_system?: string;
            };
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_json_api_v1_cases__case_id__export_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutput"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pdf_api_v1_cases__case_id__export_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF gerado com sucesso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
